"""empty message

Revision ID: 4e2254e3c474
Revises: 
Create Date: 2018-11-04 12:59:32.948309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e2254e3c474'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('themename', sa.String(length=100), nullable=True),
    sa.Column('center', sa.String(length=3), nullable=True),
    sa.Column('afdeling', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefonnr', sa.String(length=8), nullable=True),
    sa.Column('ansvarlig', sa.String(length=100), nullable=True),
    sa.Column('beskrivelse', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
