"""empty message

Revision ID: c3cafca84fb0
Revises: 
Create Date: 2018-10-30 13:28:02.349641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cafca84fb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(length=100), nullable=False),
    sa.Column('tablename', sa.String(length=100), nullable=False),
    sa.Column('center', sa.String(length=3), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ansvarlig', sa.String(length=100), nullable=True),
    sa.Column('beskrivelse', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
